language: go
go: '1.10'
git:
  depth: 1
install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
before_script:
  - echo $TRAVIS
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_PULL_REQUEST_SHA
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_SECURE_ENV_VARS
  - curl httpbin.org/ip
script:
  - make build